export const GET_PRODUCT_LOAD ="GET_PRODUCT_LOAD"
export const GET_PRODUCT_SUCCESS ="GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAIL ="GET_PRODUCT_FAIL"
export const GET_ONE_PRODUCT ="GET_ONE_CONTACT"

export const TOGGLE_TRUE ="TOGGLE_TRUE"
export const TOGGLE_FALSE ="TOGGLE_FALSE"